/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as UnauthRouteImport } from './routes/_unauth'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnauthSignUpRouteImport } from './routes/_unauth.sign-up'
import { Route as UnauthSignInRouteImport } from './routes/_unauth.sign-in'
import { Route as AuthMeRouteImport } from './routes/_auth.me'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthRoute = UnauthRouteImport.update({
  id: '/_unauth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthSignUpRoute = UnauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => UnauthRoute,
} as any)
const UnauthSignInRoute = UnauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => UnauthRoute,
} as any)
const AuthMeRoute = AuthMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/me': typeof AuthMeRoute
  '/sign-in': typeof UnauthSignInRoute
  '/sign-up': typeof UnauthSignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/me': typeof AuthMeRoute
  '/sign-in': typeof UnauthSignInRoute
  '/sign-up': typeof UnauthSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_unauth': typeof UnauthRouteWithChildren
  '/about': typeof AboutRoute
  '/_auth/me': typeof AuthMeRoute
  '/_unauth/sign-in': typeof UnauthSignInRoute
  '/_unauth/sign-up': typeof UnauthSignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/me' | '/sign-in' | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/me' | '/sign-in' | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_unauth'
    | '/about'
    | '/_auth/me'
    | '/_unauth/sign-in'
    | '/_unauth/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  UnauthRoute: typeof UnauthRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauth': {
      id: '/_unauth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauth/sign-up': {
      id: '/_unauth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof UnauthSignUpRouteImport
      parentRoute: typeof UnauthRoute
    }
    '/_unauth/sign-in': {
      id: '/_unauth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof UnauthSignInRouteImport
      parentRoute: typeof UnauthRoute
    }
    '/_auth/me': {
      id: '/_auth/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthMeRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthMeRoute: typeof AuthMeRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthMeRoute: AuthMeRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface UnauthRouteChildren {
  UnauthSignInRoute: typeof UnauthSignInRoute
  UnauthSignUpRoute: typeof UnauthSignUpRoute
}

const UnauthRouteChildren: UnauthRouteChildren = {
  UnauthSignInRoute: UnauthSignInRoute,
  UnauthSignUpRoute: UnauthSignUpRoute,
}

const UnauthRouteWithChildren =
  UnauthRoute._addFileChildren(UnauthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  UnauthRoute: UnauthRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
